### PR TITLE
added navbar, buttons, and banner. Needs some styling

### PR DESCRIPTION
**Pull request by stevespiders**
Sup guys added navbar, buttons for navigation and banner

### CODE REVIEW

**Comment by DiogoABastos** [comment]
lets talk

**Comment by mrcabral** [comment]
we are talking

**Comment by DiogoABastos** [comment]
merge?

**Comment by stevespiders** [comment]
should we????

**Comment by mrcabral** [comment]
i dunnow

**Comment by mrcabral** [comment]
DO IT!!!!

**Comment by DiogoABastos** [comment]
yes!!!!

**Pull request merged**
